# Generated by Django 5.1.3 on 2024-11-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_auto_20241126_2123"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("admin", "Administrator"),
                    ("manager", "Manager"),
                    ("staff", "Staff"),
                    ("user", "Regular User"),
                ],
                default="user",
                max_length=20,
            ),
        ),
    ]
