# Generated by Django 5.1.3 on 2024-11-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_remove_userprofile_user_type_record_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="recipient_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="record",
            name="recipient_position",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
