# Generated by Django 5.1.3 on 2024-11-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0005_record_recipient_name_record_recipient_position"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recordapproval",
            options={"ordering": ["created_at"]},
        ),
        migrations.AddField(
            model_name="record",
            name="ceo_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="record",
            name="current_approval_level",
            field=models.CharField(
                choices=[
                    ("cashier", "Cashier Review"),
                    ("deputy", "Deputy Director"),
                    ("executive", "Executive Director"),
                    ("ceo", "CEO"),
                ],
                default="cashier",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="deputy_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="record",
            name="executive_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="record",
            name="forwarded_to_deputy",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="recordapproval",
            name="approval_level",
            field=models.CharField(
                choices=[
                    ("cashier", "Cashier"),
                    ("deputy", "Deputy Director"),
                    ("executive", "Executive Director"),
                    ("ceo", "CEO"),
                ],
                default="deputy",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="record",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("pending_deputy", "Pending Deputy Director Approval"),
                    ("rejected_deputy", "Rejected by Deputy Director"),
                    ("pending_executive", "Pending Executive Director Approval"),
                    ("rejected_executive", "Rejected by Executive Director"),
                    ("pending_ceo", "Pending CEO Approval"),
                    ("rejected_ceo", "Rejected by CEO"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="recordapproval",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("pending_deputy", "Pending Deputy Director Approval"),
                    ("rejected_deputy", "Rejected by Deputy Director"),
                    ("pending_executive", "Pending Executive Director Approval"),
                    ("rejected_executive", "Rejected by Executive Director"),
                    ("pending_ceo", "Pending CEO Approval"),
                    ("rejected_ceo", "Rejected by CEO"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="recordapproval",
            unique_together={("record", "approval_level")},
        ),
    ]
