# Generated by Django 5.1.3 on 2024-11-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_alter_recordapproval_options_record_ceo_approved_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="record",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="record",
            name="lender_contact",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="record",
            name="lender_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("income", "Income"),
                    ("expense", "Expense"),
                    ("advance", "Advance"),
                    ("balance", "Balance"),
                    ("payable", "Payable"),
                ],
                max_length=20,
            ),
        ),
    ]
