# Generated by Django 5.1.3 on 2024-11-28 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "website",
            "0007_record_due_date_record_is_paid_record_lender_contact_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 11, 28, 8, 34, 3, 696921, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="record",
            name="repayment_deadline",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="record",
            name="repayment_method",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
