# Generated by Django 5.1.3 on 2024-11-28 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0008_record_date_record_repayment_deadline_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="read",
            new_name="is_read",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="link",
        ),
        migrations.AddField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("record_approval", "Record Approval"),
                    ("record_status", "Record Status Change"),
                    ("record_comment", "Record Comment"),
                    ("system", "System Notification"),
                ],
                default="system",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="website.record",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["-created_at"], name="website_not_created_a12bd5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read"], name="website_not_user_id_5accc9_idx"
            ),
        ),
    ]
