# Generated by Django 5.0.1 on 2024-11-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('data_entry', 'Data Entry'), ('cashier', 'Cashier'), ('regular', 'Regular User')], default='regular', max_length=20),
        ),
    ]
