# Generated by Django 5.1.3 on 2024-11-28 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="budget",
            options={"verbose_name": "Budget", "verbose_name_plural": "Budgets"},
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
            },
        ),
    ]
